### ISSUE TITLE
1.0.6 and 1.0.7 breaks bower

### ISSUE THREAD

**Issue by kbenjamin** [npm/fs-write-stream-atomic#11]
bower users are seeing a variety of issues since bumping the dependency on fs-write-stream-atomic up from 1.0.5 to 1.0.7:

https://github.com/bower/bower/issues/2118 (known and proven)
https://github.com/bower/bower/issues/2101 (suspected)
https://ci.appveyor.com/project/bodil/pulp/build/1.0.67 (suspected)

This is an example of the sorts of errors that are being seen, although there are several others mentioned. Note that they occur seemingly randomly, perhaps due to timing issues or an improperly handled async operation:

```
bower install
...
bower paper-menu#^1.0.0                             extract archive.tar.gz
bower iron-validatable-behavior#^1.0.0              extract archive.tar.gz
bower platinum-https-redirect#^1.0.0                extract archive.tar.gz
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, rename 'C:\Users\Ken\AppData\Local\Temp\mypc-Ken\bower\cefb8f774d98384ed30dec610f03a72d-174564-wZPTqe\archive.tar.gz.207942742'
    at Error (native)
```

Downgrading to 1.0.5 resolves the issue (tested for https://github.com/bower/bower/issues/2118)

**Comment by iarna** [comment]
These should be fixed by 1.0.8

**Comment by iarna** [comment]
I've deprecated 1.0.6 and 1.0.7 with an appropriate warning, so I'm going to close this.

**Comment by samccone** [comment]
:+1: thanks @iarna
